### ISSUE TITLE
ARN's with wildcarded service fail

### ISSUE THREAD

**Issue by garnaat** [scopely-devops/skew#46]
If you have an ARN like:

    arn:aws:*:*:*:*/*

and you try to enumerate it, you get the error:

    KeyError: 'aws.autoscaling.*'"

Substituting the wildcard with a specific service works correctly.

**Comment by garnaat** [comment]
@solarce this should fix the issue you were having

**Comment by solarce** [comment]
Thank you @garnaat !!

**Comment by HenryTheHamster** [comment]
Hi @garnaat - great utility, thank you very much.

Using the same ARN pattern as above for us yields:

`ValueError: Invalid endpoint: https://iam..amazonaws.com`

Running version `0.16.1`

**Comment by mholtby** [comment]
Yep, mine does that too. The API endpoint for Global AWS services doesn't have the region and therefore breaks. I tried to get round it by using an ARN that misses the region in my script but that didn't help.

#!/usr/bin/env python
import skew
from skew.arn import ARN
arn = ARN()
services=arn.service.choices()
services.sort()
#services=["route53", "iam"]
print('Enumerating all resources in the following services: ' + ' '.join(services) + '\n')
for service in services:
  #skipping global services because the API endpoint fails due to it being a global service. Bug that needs fixing.
  if service == "iam" or service == "route53":
    print(service)  
    print('Skipping global services')
    #uri = 'arn:aws:' + service + '::_:_/_'
    #arn = skew.scan(uri)
    #for i in arn:
    #  print(i.arn)
  else:
    print('_****_' + service + '**_**_')
    uri = 'arn:aws:' + service + ':_:_:_/*'
    arn = skew.scan(uri)
    for i in arn:
      print(i.arn)

@garnaat - is this a known issue?
